### ISSUE TITLE
Production Bastion Host

### ISSUE THREAD

**Issue by nilesh93** [ECLK/Deployment#26]
Bastion host should have

A public IP Address

NFS mount on  /data
mysql client connected to prod mysql server
Kubectl connected to prod k8s server
Helm connected to prod k8s server

**Comment by sanjiva** [comment]
Sanjiva to request additional public IP from ICTA LGC.

**Comment by sanjiva** [comment]
This IP has been provided to us. 

Please close this issue when set up is completed.
