### ISSUE TITLE
Production Alert Resources

### ISSUE THREAD

**Issue by nilesh93** [ECLK/Deployment#36]
Identify the alerts that are needed.
Get the list of emails
Get the list of Phone numbers
Get any other social messaging platforms required (Slack, Google chat etc)

**Comment by nshamit** [comment]
The EC team is filling in the information [https://docs.google.com/spreadsheets/d/1pEbrrtxVub6MNXXpvejPoXvIW7gusg3S707sDryH4S0/edit?usp=sharing]

**Comment by sanjiva** [comment]
We've sorted this out  - closing.
