### ISSUE TITLE
Deploy staffing system backend APIs for dev environment

### ISSUE THREAD

**Issue by sanjiva** [ECLK/Deployment#45]
The process is:
- repo: Staffing/backend
- build: ballerina build services
   will produce target/bin/services.jar
- build docker image using Alpine Linux OpenJDK image
- command to RUN is java -jar services.jar
- map port 80 to port 9090
- temporary (proper fix is to expose under API manager)
  - create a new k8s service called "staffing-backend" for this service

**Comment by sanjiva** [comment]
Sample Dockerfile:

FROM openjdk:8-jre-alpine
LABEL maintainer="dev@ballerina.io"

WORKDIR /home/ballerina
COPY k8s.jar /home/ballerina 

EXPOSE  8080
CMD java -jar k8s.jar

**Comment by sanjiva** [comment]
Kosala please use this Docker image to build the program:

https://hub.docker.com/r/ballerina/ballerina

Build command is:
```
ballerina build services
```

**Comment by kosalag** [comment]
deployed on https://api.staffing.ecdev.opensource.lk
