### ISSUE TITLE
Deploy results distribution app to dev

### ISSUE THREAD

**Issue by sanjiva** [ECLK/Deployment#48]
The code is not yet committed but it will be soon :-).

The structure of the code will be like the backend of the Staffing app as its being written in Ballerina. 

The system has a website for media people to login and access and also has a mechanism to push the data out (via registered webhooks). The webhook subscription URL has to be open to anyone to access (details will be given). We haven't yet decided whether to use IS for authentication or not but we can decide that later.

Lets set up mediaresults.ecdev.opensource.lk as the host please.

The build and deploy process will be same as for Staffing.

**Comment by sanjiva** [comment]
Code committed.

**Comment by sanjiva** [comment]
Build instructions:

Copy the contents of `ECLK/Results-Dist/deployment-utils/` to the Ballerina installation's distribution `ballerina/ballerina-1.0.1/distributions/jballerina-1.0.1/`

```cd /Results-Dist/distributor/```

Build the pubhub module to generate the executable

```ballerina build pubhub --eclk.hub.db.url=jdbc:mysql://<DB_URL> --eclk.hub.db.username=<DB_UN> --eclk.hub.db.password=<DB_PW> --eclk.hub.db.useSsl=<DB_USE_SSL> --eclk.hub.db.encryptionkey=<DB_ENCRYPTION_KEY>```

Build the docker image, use the following run command:
```ballerina run target/bin/pubhub.jar --eclk.hub.db.url=jdbc:mysql://<DB_URL> --eclk.hub.db.username=<DB_UN> --eclk.hub.db.password=<DB_PW> --eclk.hub.db.useSsl=<DB_USE_SSL> --eclk.hub.db.encryptionkey=<DB_ENCRYPTION_KEY>```

**Comment by sanjiva** [comment]
Relates to #50

**Comment by kosalag** [comment]
Deployed on dev
URLs are
https://dist.results.ecdev.opensource.lk - port 9090
https://pushresult.ecdev.opensource.lk - port 8181

**Comment by sanjiva** [comment]
I've made some significant changes to the way the code is organized.

Now to build please use the "distributor" directory and type `ballerina build --skip-tests distributor`

For the DNS names, please do as follows:
- port 9090 should go as mediaresultshub.ecdev.opensource.lk and is publicly open
- port 8181 will eventually NOT be open to others but will be called directly from tabulation. FOR NOW, please expose as you have: publishresult.evdev.opensource.lk. Later we will keep the same name but not put it to the ingress.

There will soon be one more port to expose as well.

**Comment by kosalag** [comment]
Deployed
port 9090 on mediaresultshub.ecdev.opensource.lk
port 8181 on publishresult.ecdev.opensource.lk
