### ISSUE TITLE
Deploy results tabulation user admin app to dev

### ISSUE THREAD

**Issue by sanjiva** [ECLK/Deployment#49]
Repo location: https://github.com/ECLK/results-tabulation-admin-app.

Please deploy as: resultstabadmin.ecdev.opensource.lk.

**Comment by sanjiva** [comment]
Build instructions:

Copy the contents of `ECLK/Results-Dist/deployment-utils/` to the Ballerina installation's distribution `ballerina/ballerina-1.0.1/distributions/jballerina-1.0.1/`

```cd /Results-Dist/distributor/```

Build the `pubhub` module to generate the executable
```
ballerina build pubhub --eclk.hub.db.url=jdbc:mysql://<DB_URL> --eclk.hub.db.username=<DB_UN> --eclk.hub.db.password=<DB_PW> --eclk.hub.db.useSsl=<DB_USE_SSL> --eclk.hub.db.encryptionkey=<DB_ENCRYPTION_KEY>```

Build the docker image, use the following run command:
```ballerina run target/bin/pubhub.jar --eclk.hub.db.url=jdbc:mysql://<DB_URL> --eclk.hub.db.username=<DB_UN> --eclk.hub.db.password=<DB_PW> --eclk.hub.db.useSsl=<DB_USE_SSL> --eclk.hub.db.encryptionkey=<DB_ENCRYPTION_KEY>```

**Comment by kosalag** [comment]
done
